# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: House of Maldorne
subtitle: 'Retro gaming association'
description: 'We play, host, build, develop and recover old and new retro online games, from muds to roguelikes.'
keywords:
language: en
timezone: ''
author: neverbot

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://maldorne.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
  # lang: en
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_render:

# Writing
new_post_name: :year/:month/:day/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

post_asset_folder: true
# marked:
#   prependRoot: true
#   postAsset: true
markdown:
  plugins:
    markdown-it-texmath:
      disabled: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date

# Category & Tag
default_category: uncategorized
category_map:  
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: maldorne

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

# hexo-generator-feed config
feed:
  enable: true
  type: ['atom', 'rss2']
  path: atom.xml/rss2.xml
  limit: 20
  hub:
  content: true
  # content_limit: 140
  # content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# giscus comments
giscus:
  repo: maldorne/maldorne.org
  repoid: MDEwOlJlcG9zaXRvcnkyMzI4NTc5OTk=
  category: Posts
  categoryid: DIC_kwDODeEhj84Cg554
  mapping: title
